package com.ryan.centralsale.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.ryan.centralsale.model.dto.ProductDTO;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
@Transactional
@RequiredArgsConstructor
public class ProductService {

    private final WebClient.Builder webClientBuilder; // used for making HTTP requests with Rainforest API
    private final ObjectMapper objectMapper; // used for parsing our JSON response

    @Value("${rainforest.api.key}")
    private String rainforestApiKey; // API key for authenticating requests to Rainforest API

    private WebClient webClient;

    private WebClient getWebClient() {
        if (webClient == null) {
            webClient = webClientBuilder
                    .baseUrl("https://api.rainforestapi.com")
                    .build();
        }
        return webClient;
    }

    public ProductDTO fetchProductData(String asin) {
        return webClient.get()
                .uri(uriBuilder -> uriBuilder
                        .path("/request")
                        .queryParam("api_key", rainforestApiKey)
                        .queryParam("type", "product")
                        .queryParam("amazon_domain", "amazon.com")
                        .queryParam("asin", asin)
                        .build())
                .retrieve()
                .bodyToMono(String.class)
                .<ProductDTO>handle((response, sink) -> {
                    try {
                        // Parse JSON response to ProductDTO
                        sink.next(objectMapper.readValue(response, ProductDTO.class));
                    } catch (Exception e) {
                        sink.error(new RuntimeException("Failed to parse product data", e));
                    }
                })
                .block(); // Block to get the result synchronously
    }

    /**
     * Extract ASIN from Amazon URL (Generated by Co Pilot)
     * @param url Amazon product URL
     * @return Optional containing ASIN if found, otherwise empty
     */
    public Optional<String> extractAsinFromUrl(String url) {
        // Pattern matches: /dp/ASIN or /gp/product/ASIN
        Pattern pattern = Pattern.compile("/(?:dp|gp/product)/([A-Z0-9]{10})");
        Matcher matcher = pattern.matcher(url);

        if (matcher.find()) {
            return Optional.of(matcher.group(1));
        }
        return Optional.empty();
    }


}
